#DICTIONARY

DATA = {
    "AGING" : "The reduction of insulation life due to thermal, voltage and other stress.",
    "AIR GAP" : "Short gap in the magnetic material forming a magnetic.",
    "BRUSH" : "A sliding electrical contact, usually rotating.",
    "CAPACITANCE" : "The amount of electrical energy stored for a given electrical potential.",
    "COIL" : "Set of series of connected turns.",
    "DATA BLOCK" : "A sequence of data in bits or bytes that are usually transferred as a whole.",
    "DIGITAL" : "A system in which all the information and signals are represented by binary numbers or discrete values.",
    "EARPHONE" : "A small piece of equipment that converts electrical waves into soundwaves.",
    "ELECTROMETER" : "A voltage measuring equipment that measures the electrical potential difference between two charged bodies without drawing any current from the source.",
    "FAILURE" : "The malfunctioning of a device or a component that does not achieve desired target.",
    "GAMMA" : "A unit of magnetic intensity equal to 10-5 oersted.",
    "HALT" : "A command that is used to stop operation either permanently or temporarily.",
    "IMPLOSION" : "The sudden inward collapse.",
    "JACK SCREW" : "A screw-operated jack for lifting, exerting pressure or adjusting position.",
    "KEYBOARD" : "A peripheral device that is used as data input for a computer.",
    "LADDER" : "A circuit structure using components connected in a chain.",
    "MASKING" : "A process in which only required data is retained and the rest is blocked, it can be using bitwise operators.",
    "NEGATE" : "In Boolean algebra, Negate means complements.",
    "OBSOLETE" : "These are products which are no longer manufactured or discontinued due to replacement of advanced function.",
    "PART" : "A single component/device or a permanent assemble of more than one part that is intended to be part of somethine else.",
    "QUINT" : "A sequence of five individual circuit blocks within the same IC package.",
    "RADIAN" : "A unit of angulare measurement that is equal to the length that corresponds to the unit circle. 1rad = 57.3 degress.",
    "SATELLITE" : "An artificial celestial body that is placed in orbit to round the planet in order to collect information or to establish a better communication network.",
    "TAP" : "A fixed intermediate point in an electrical from which connections can be made.",
    "UNIT" : "A single device or a group of devices that can operate itself and can also be assembled together to execute more complex actions.",
    "VACUUM" : "An encolsed area of space that is relatively empty of matter.",
    "WAVE" : "A pattern of disturbance generated by the movement of energy propagating through a medium from one location to another.",
    "X-AXIS" : "A horizontal reference axis in a two dimensional coordinate system/graph.",
    "Y-AXIS" : "A vertical reference axis in a two dimensional coordinate system/graph.",
    "ZERO POTENTIAL" : "The potential across the ground terminal in any electrical circuit.",
    
    }

a = input("SEARCH:")
print(DATA[a])